projectId: app-BoKpGiTPF9kLvCajuReyAT
appName: onlineboutique
description: Sample application
imageURL: http://image.com/image
version: 1.0.0
hostName: example.test
clusterURL: https://kubernetes.default.svc
clusterIPs:
- 192.168.59.103
microservices:
  adservice:
    serviceName: adservice
  cartservice:
    serviceName: cartservice
    serviceEvaluation:
      kubeConfigType:
      - statefulSetBased
  checkoutservice:
    serviceName: checkoutservice
  currencyservice:
    serviceName: currencyservice
  emailservice:
    serviceName: emailservice
  paymentservice:
    serviceName: paymentservice
  productcatalogservice:
    serviceName: productcatalogservice
  recommendationservice:
    serviceName: recommendationservice
  shippingservice:
    serviceName: shippingservice
evaluationResult:
  language: Java
  hasKubernetesService: true
  hasKubernetesDeployment: true
  microservices:
  - adservice
  - cartservice
  - checkoutservice
  - currencyservice
  - emailservice
  - paymentservice
  - productcatalogservice
  - recommendationservice
  - shippingservice
