projectId: app-dPRVshYfTfk97LvVfa2e35
appName: cineroam
description: Sample application
imageURL: http://image.com/image
version: 1.0.0
hostName: example.test
clusterURL: https://kubernetes.default.svc
clusterIPs:
- 192.168.59.103
monitoring: true
microservices:
  movie-microservice:
    serviceName: moviemicroservice
  recommendation-microservice:
    serviceName: recommendationmicroservice
  user-microservice:
    serviceName: usermicroservice
    serviceEvaluation:
      kubeConfigType:
      - statefulSetBased
evaluationResult:
  language: Go
  database: Mongo
  microservices:
  - movie-microservice
  - recommendation-microservice
  - user-microservice
