projectId: app-cTTY2tRPnQLEeqecLNEhwW
appName: petclinic
description: Sample application
imageURL: http://image.com/image
version: 1.0.0
hostName: example.test
clusterURL: https://kubernetes.default.svc
clusterIPs:
- 192.168.59.103
monitoring: true
microservices:
  petclinicService:
    serviceName: petclinicservice
  service:
    serviceName: service
    serviceEvaluation:
      kubeConfigType:
      - statefulSetBased
evaluationResult:
  language: Java
  database: MySQL
  microservices:
  - petclinicService
  - service
